import localFont from "next/font/local";
import "./globals.css";
import VerticalNavBar from "./components/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
        bg-[#3C3D37] flex font-sans 

        
        `}
      >
        <VerticalNavBar  />
        <main className="flex-1 p-5  min-h-screen sm:ml-0 lg:ml-44">{children}</main>
      </body>
    </html>
  );
}
